compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: no
dynamo_config: {}
fsdp_config: {}
gpu_ids: 0,1,3,4,5,6
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: bf16
num_machines: 1
num_processes: 6
rdzv_backend: static
same_network: true
use_cpu: false
